# Generated by Django 3.2.4 on 2022-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0003_auto_20220226_0304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackForm',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
